# Generated by Django 2.1.4 on 2019-01-09 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributevalue',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='catalog.Product'),
        ),
    ]
