# Generated by Django 2.1.3 on 2018-12-18 04:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='rev',
            field=models.CharField(default='1-ac6452fe-1337-4201-8e1a-1082ad237290', editable=False, max_length=38, verbose_name='Ревизия'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('99df434f-f57b-41df-906c-ec1267a3ce76'), editable=False, primary_key=True, serialize=False, verbose_name='Когда создано'),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='rev',
            field=models.CharField(default='1-ac6452fe-1337-4201-8e1a-1082ad237290', editable=False, max_length=38, verbose_name='Ревизия'),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('99df434f-f57b-41df-906c-ec1267a3ce76'), editable=False, primary_key=True, serialize=False, verbose_name='Когда создано'),
        ),
        migrations.AlterField(
            model_name='category',
            name='rev',
            field=models.CharField(default='1-ac6452fe-1337-4201-8e1a-1082ad237290', editable=False, max_length=38, verbose_name='Ревизия'),
        ),
        migrations.AlterField(
            model_name='category',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('99df434f-f57b-41df-906c-ec1267a3ce76'), editable=False, primary_key=True, serialize=False, verbose_name='Когда создано'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='rev',
            field=models.CharField(default='1-ac6452fe-1337-4201-8e1a-1082ad237290', editable=False, max_length=38, verbose_name='Ревизия'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('99df434f-f57b-41df-906c-ec1267a3ce76'), editable=False, primary_key=True, serialize=False, verbose_name='Когда создано'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rev',
            field=models.CharField(default='1-ac6452fe-1337-4201-8e1a-1082ad237290', editable=False, max_length=38, verbose_name='Ревизия'),
        ),
        migrations.AlterField(
            model_name='product',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('99df434f-f57b-41df-906c-ec1267a3ce76'), editable=False, primary_key=True, serialize=False, verbose_name='Когда создано'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='rev',
            field=models.CharField(default='1-ac6452fe-1337-4201-8e1a-1082ad237290', editable=False, max_length=38, verbose_name='Ревизия'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('99df434f-f57b-41df-906c-ec1267a3ce76'), editable=False, primary_key=True, serialize=False, verbose_name='Когда создано'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='rev',
            field=models.CharField(default='1-ac6452fe-1337-4201-8e1a-1082ad237290', editable=False, max_length=38, verbose_name='Ревизия'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('99df434f-f57b-41df-906c-ec1267a3ce76'), editable=False, primary_key=True, serialize=False, verbose_name='Когда создано'),
        ),
    ]
