# Generated by Django 2.1.4 on 2018-12-19 04:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20181218_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='rev',
            field=models.CharField(default='1-ea8e605e-1718-4976-bc80-fe2c1b9b1ff7', editable=False, max_length=38, verbose_name='Ревизия'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('04450fff-9a50-4de7-9631-4abef6355ad8'), editable=False, primary_key=True, serialize=False, verbose_name='Когда создано'),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='rev',
            field=models.CharField(default='1-ea8e605e-1718-4976-bc80-fe2c1b9b1ff7', editable=False, max_length=38, verbose_name='Ревизия'),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('04450fff-9a50-4de7-9631-4abef6355ad8'), editable=False, primary_key=True, serialize=False, verbose_name='Когда создано'),
        ),
        migrations.AlterField(
            model_name='category',
            name='rev',
            field=models.CharField(default='1-ea8e605e-1718-4976-bc80-fe2c1b9b1ff7', editable=False, max_length=38, verbose_name='Ревизия'),
        ),
        migrations.AlterField(
            model_name='category',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('04450fff-9a50-4de7-9631-4abef6355ad8'), editable=False, primary_key=True, serialize=False, verbose_name='Когда создано'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='rev',
            field=models.CharField(default='1-ea8e605e-1718-4976-bc80-fe2c1b9b1ff7', editable=False, max_length=38, verbose_name='Ревизия'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('04450fff-9a50-4de7-9631-4abef6355ad8'), editable=False, primary_key=True, serialize=False, verbose_name='Когда создано'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rev',
            field=models.CharField(default='1-ea8e605e-1718-4976-bc80-fe2c1b9b1ff7', editable=False, max_length=38, verbose_name='Ревизия'),
        ),
        migrations.AlterField(
            model_name='product',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('04450fff-9a50-4de7-9631-4abef6355ad8'), editable=False, primary_key=True, serialize=False, verbose_name='Когда создано'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='rev',
            field=models.CharField(default='1-ea8e605e-1718-4976-bc80-fe2c1b9b1ff7', editable=False, max_length=38, verbose_name='Ревизия'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('04450fff-9a50-4de7-9631-4abef6355ad8'), editable=False, primary_key=True, serialize=False, verbose_name='Когда создано'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='rev',
            field=models.CharField(default='1-ea8e605e-1718-4976-bc80-fe2c1b9b1ff7', editable=False, max_length=38, verbose_name='Ревизия'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('04450fff-9a50-4de7-9631-4abef6355ad8'), editable=False, primary_key=True, serialize=False, verbose_name='Когда создано'),
        ),
    ]
