# Generated by Django 2.1.3 on 2018-12-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20181207_0753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='attributevalue',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='attributevalue',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='category',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='category',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='specification',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='specification',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='attribute',
            name='id',
            field=models.UUIDField(default='8d06a7207cd24a6e9939c15c2ccb8816', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='rev',
            field=models.CharField(default='1-5ede8ee7553844dc9923c03a73e9c8fe', editable=False, max_length=64, verbose_name='Ревизия'),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='id',
            field=models.UUIDField(default='8d06a7207cd24a6e9939c15c2ccb8816', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='rev',
            field=models.CharField(default='1-5ede8ee7553844dc9923c03a73e9c8fe', editable=False, max_length=64, verbose_name='Ревизия'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default='8d06a7207cd24a6e9939c15c2ccb8816', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='rev',
            field=models.CharField(default='1-5ede8ee7553844dc9923c03a73e9c8fe', editable=False, max_length=64, verbose_name='Ревизия'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='id',
            field=models.UUIDField(default='8d06a7207cd24a6e9939c15c2ccb8816', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='rev',
            field=models.CharField(default='1-5ede8ee7553844dc9923c03a73e9c8fe', editable=False, max_length=64, verbose_name='Ревизия'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='id',
            field=models.UUIDField(default='8d06a7207cd24a6e9939c15c2ccb8816', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='rev',
            field=models.CharField(default='1-5ede8ee7553844dc9923c03a73e9c8fe', editable=False, max_length=64, verbose_name='Ревизия'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default='8d06a7207cd24a6e9939c15c2ccb8816', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='rev',
            field=models.CharField(default='1-5ede8ee7553844dc9923c03a73e9c8fe', editable=False, max_length=64, verbose_name='Ревизия'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='id',
            field=models.UUIDField(default='8d06a7207cd24a6e9939c15c2ccb8816', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='specification',
            name='rev',
            field=models.CharField(default='1-5ede8ee7553844dc9923c03a73e9c8fe', editable=False, max_length=64, verbose_name='Ревизия'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='id',
            field=models.UUIDField(default='8d06a7207cd24a6e9939c15c2ccb8816', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='rev',
            field=models.CharField(default='1-5ede8ee7553844dc9923c03a73e9c8fe', editable=False, max_length=64, verbose_name='Ревизия'),
        ),
    ]
