# Generated by Django 2.1.4 on 2018-12-19 04:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20181219_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='rev',
            field=models.CharField(default='1-beea0087-2cdb-4fae-aa3e-b5559787130f', max_length=38, verbose_name='Ревизия'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('b602050a-7c1d-44a8-a3eb-b1b149332cc7'), editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='rev',
            field=models.CharField(default='1-beea0087-2cdb-4fae-aa3e-b5559787130f', max_length=38, verbose_name='Ревизия'),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('b602050a-7c1d-44a8-a3eb-b1b149332cc7'), editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='category',
            name='rev',
            field=models.CharField(default='1-beea0087-2cdb-4fae-aa3e-b5559787130f', max_length=38, verbose_name='Ревизия'),
        ),
        migrations.AlterField(
            model_name='category',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('b602050a-7c1d-44a8-a3eb-b1b149332cc7'), editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='rev',
            field=models.CharField(default='1-beea0087-2cdb-4fae-aa3e-b5559787130f', max_length=38, verbose_name='Ревизия'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('b602050a-7c1d-44a8-a3eb-b1b149332cc7'), editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rev',
            field=models.CharField(default='1-beea0087-2cdb-4fae-aa3e-b5559787130f', max_length=38, verbose_name='Ревизия'),
        ),
        migrations.AlterField(
            model_name='product',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('b602050a-7c1d-44a8-a3eb-b1b149332cc7'), editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='rev',
            field=models.CharField(default='1-beea0087-2cdb-4fae-aa3e-b5559787130f', max_length=38, verbose_name='Ревизия'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('b602050a-7c1d-44a8-a3eb-b1b149332cc7'), editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='rev',
            field=models.CharField(default='1-beea0087-2cdb-4fae-aa3e-b5559787130f', max_length=38, verbose_name='Ревизия'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('b602050a-7c1d-44a8-a3eb-b1b149332cc7'), editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор'),
        ),
    ]
