# Generated by Django 2.1.4 on 2018-12-19 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20181219_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Когда создано'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кем создано'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='deleted',
            field=models.BooleanField(default=False, editable=False, verbose_name='В архиве?'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='rev',
            field=models.CharField(default='1-0556b095-dfd4-42af-8691-43bc9894f18b', editable=False, max_length=38, verbose_name='Ревизия'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('9c462358-28a7-4c1a-b2b3-5ba200141cdd'), editable=False, primary_key=True, serialize=False, verbose_name='Когда создано'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Когда обновлено'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='updated_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кем обновлено'),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Когда создано'),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кем создано'),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='deleted',
            field=models.BooleanField(default=False, editable=False, verbose_name='В архиве?'),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='rev',
            field=models.CharField(default='1-0556b095-dfd4-42af-8691-43bc9894f18b', editable=False, max_length=38, verbose_name='Ревизия'),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('9c462358-28a7-4c1a-b2b3-5ba200141cdd'), editable=False, primary_key=True, serialize=False, verbose_name='Когда создано'),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Когда обновлено'),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='updated_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кем обновлено'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Когда создано'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кем создано'),
        ),
        migrations.AlterField(
            model_name='category',
            name='deleted',
            field=models.BooleanField(default=False, editable=False, verbose_name='В архиве?'),
        ),
        migrations.AlterField(
            model_name='category',
            name='rev',
            field=models.CharField(default='1-0556b095-dfd4-42af-8691-43bc9894f18b', editable=False, max_length=38, verbose_name='Ревизия'),
        ),
        migrations.AlterField(
            model_name='category',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('9c462358-28a7-4c1a-b2b3-5ba200141cdd'), editable=False, primary_key=True, serialize=False, verbose_name='Когда создано'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Когда обновлено'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кем обновлено'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Когда создано'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кем создано'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='deleted',
            field=models.BooleanField(default=False, editable=False, verbose_name='В архиве?'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='rev',
            field=models.CharField(default='1-0556b095-dfd4-42af-8691-43bc9894f18b', editable=False, max_length=38, verbose_name='Ревизия'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('9c462358-28a7-4c1a-b2b3-5ba200141cdd'), editable=False, primary_key=True, serialize=False, verbose_name='Когда создано'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Когда обновлено'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='updated_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кем обновлено'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Когда создано'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кем создано'),
        ),
        migrations.AlterField(
            model_name='product',
            name='deleted',
            field=models.BooleanField(default=False, editable=False, verbose_name='В архиве?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rev',
            field=models.CharField(default='1-0556b095-dfd4-42af-8691-43bc9894f18b', editable=False, max_length=38, verbose_name='Ревизия'),
        ),
        migrations.AlterField(
            model_name='product',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('9c462358-28a7-4c1a-b2b3-5ba200141cdd'), editable=False, primary_key=True, serialize=False, verbose_name='Когда создано'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Когда обновлено'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кем обновлено'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Когда создано'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кем создано'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='deleted',
            field=models.BooleanField(default=False, editable=False, verbose_name='В архиве?'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='rev',
            field=models.CharField(default='1-0556b095-dfd4-42af-8691-43bc9894f18b', editable=False, max_length=38, verbose_name='Ревизия'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('9c462358-28a7-4c1a-b2b3-5ba200141cdd'), editable=False, primary_key=True, serialize=False, verbose_name='Когда создано'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Когда обновлено'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='updated_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кем обновлено'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Когда создано'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кем создано'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='deleted',
            field=models.BooleanField(default=False, editable=False, verbose_name='В архиве?'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='rev',
            field=models.CharField(default='1-0556b095-dfd4-42af-8691-43bc9894f18b', editable=False, max_length=38, verbose_name='Ревизия'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('9c462358-28a7-4c1a-b2b3-5ba200141cdd'), editable=False, primary_key=True, serialize=False, verbose_name='Когда создано'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Когда обновлено'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='updated_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кем обновлено'),
        ),
    ]
