# Generated by Django 2.1.3 on 2018-12-07 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0007_auto_20181207_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='created_by',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кем создано'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attribute',
            name='updated_by',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кем обновлено'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='created_by',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кем создано'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='updated_by',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кем обновлено'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='created_by',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кем создано'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='updated_by',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кем обновлено'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='created_by',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кем создано'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='updated_by',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кем обновлено'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='created_by',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кем создано'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='updated_by',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кем обновлено'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кем создано'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='updated_by',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кем обновлено'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specification',
            name='created_by',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кем создано'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specification',
            name='updated_by',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кем обновлено'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='created_by',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кем создано'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='updated_by',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кем обновлено'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attribute',
            name='id',
            field=models.UUIDField(default='c453f160a7014dd5ac1cb93e8c230e19', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='rev',
            field=models.CharField(default='1-59b5f99bfbbb453f80017642a132b8b7', editable=False, max_length=64, verbose_name='Ревизия'),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='id',
            field=models.UUIDField(default='c453f160a7014dd5ac1cb93e8c230e19', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='rev',
            field=models.CharField(default='1-59b5f99bfbbb453f80017642a132b8b7', editable=False, max_length=64, verbose_name='Ревизия'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default='c453f160a7014dd5ac1cb93e8c230e19', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='rev',
            field=models.CharField(default='1-59b5f99bfbbb453f80017642a132b8b7', editable=False, max_length=64, verbose_name='Ревизия'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='id',
            field=models.UUIDField(default='c453f160a7014dd5ac1cb93e8c230e19', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='rev',
            field=models.CharField(default='1-59b5f99bfbbb453f80017642a132b8b7', editable=False, max_length=64, verbose_name='Ревизия'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='id',
            field=models.UUIDField(default='c453f160a7014dd5ac1cb93e8c230e19', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='rev',
            field=models.CharField(default='1-59b5f99bfbbb453f80017642a132b8b7', editable=False, max_length=64, verbose_name='Ревизия'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default='c453f160a7014dd5ac1cb93e8c230e19', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='rev',
            field=models.CharField(default='1-59b5f99bfbbb453f80017642a132b8b7', editable=False, max_length=64, verbose_name='Ревизия'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='id',
            field=models.UUIDField(default='c453f160a7014dd5ac1cb93e8c230e19', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='specification',
            name='rev',
            field=models.CharField(default='1-59b5f99bfbbb453f80017642a132b8b7', editable=False, max_length=64, verbose_name='Ревизия'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='id',
            field=models.UUIDField(default='c453f160a7014dd5ac1cb93e8c230e19', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='rev',
            field=models.CharField(default='1-59b5f99bfbbb453f80017642a132b8b7', editable=False, max_length=64, verbose_name='Ревизия'),
        ),
    ]
