# Generated by Django 2.1.4 on 2018-12-19 04:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20181219_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='rev',
            field=models.CharField(default='1-170f42cb-9c94-415d-8951-72f828a5f269', editable=False, max_length=38, verbose_name='Ревизия'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Когда создано'),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='rev',
            field=models.CharField(default='1-170f42cb-9c94-415d-8951-72f828a5f269', editable=False, max_length=38, verbose_name='Ревизия'),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Когда создано'),
        ),
        migrations.AlterField(
            model_name='category',
            name='rev',
            field=models.CharField(default='1-170f42cb-9c94-415d-8951-72f828a5f269', editable=False, max_length=38, verbose_name='Ревизия'),
        ),
        migrations.AlterField(
            model_name='category',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Когда создано'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='rev',
            field=models.CharField(default='1-170f42cb-9c94-415d-8951-72f828a5f269', editable=False, max_length=38, verbose_name='Ревизия'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Когда создано'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rev',
            field=models.CharField(default='1-170f42cb-9c94-415d-8951-72f828a5f269', editable=False, max_length=38, verbose_name='Ревизия'),
        ),
        migrations.AlterField(
            model_name='product',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Когда создано'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='rev',
            field=models.CharField(default='1-170f42cb-9c94-415d-8951-72f828a5f269', editable=False, max_length=38, verbose_name='Ревизия'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Когда создано'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='rev',
            field=models.CharField(default='1-170f42cb-9c94-415d-8951-72f828a5f269', editable=False, max_length=38, verbose_name='Ревизия'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Когда создано'),
        ),
    ]
